In [ ]:
import numpy as np

In [ ]:
my_list = list(range(100000)) #normal

my_array = np.array(range(100000)) #numpy massiv - vektorlashgan

In [ ]:
%time for i in range(10): [x*2 for x in my_list]

CPU times: user 113 ms, sys: 10.8 ms, total: 124 ms
Wall time: 128 ms


In [ ]:
%time for i in range(10): my_array*2

CPU times: user 2.49 ms, sys: 0 ns, total: 2.49 ms
Wall time: 5.14 ms


In [ ]:
128/5.14


24.90272373540856

In [ ]:
data1 = [3,6,7,8]
arr = np.array(data1)

In [ ]:
arr

array([3, 6, 7, 8])

In [ ]:
data2 = (3,6,7,8,3)
arr2 = np.array(data2)

In [ ]:
arr2

array([3, 6, 7, 8, 3])

In [ ]:
arr.ndim

1

In [ ]:
arr2.ndim  #array ning o'lchamini aniqlash


1

In [ ]:
data3 = [[1,2,4,5] ,[4,6,5,3]] #nested list(massiv ichidagi massiv)
arr3 = np.array(data3)

In [ ]:
arr3

array([[1, 2, 4, 5],
       [4, 6, 5, 3]])

In [ ]:
arr3.ndim


2

In [ ]:
data4 = [[[1, 2, 3], ["a", "b", "c"], [True, False, None]],
[[1, 2, 3], ["a", "b", "c"], [True, False, None]],
[[1, 2, 3], ["a", "b", "c"], [True, False, None]]]
arr4 = np.array(data4)
print(arr4)

[[[1 2 3]
  ['a' 'b' 'c']
  [True False None]]

 [[1 2 3]
  ['a' 'b' 'c']
  [True False None]]

 [[1 2 3]
  ['a' 'b' 'c']
  [True False None]]]


In [ ]:
arr4.ndim

2

In [ ]:
arr3.shape


(2, 4)

In [ ]:
arr4.shape

(3,)

In [ ]:
arr3.size

8

In [ ]:
arr5 = [
    [
        [
            [12,53,2,3],
             [44343,56,4,],
              [34,5,6,4]
            ]
        ]
    ]
arr6 = np.array(arr5)
arr6.ndim

<ipython-input-41-e54c450207f7>:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr6 = np.array(arr5)


2

In [ ]:
arr6 = np.arange(4,20, 2)
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr7 = np.arange(20)
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
import numpy as np
arr0 = np.arange(2,20, 2)
arr0
arr0.ndim

arr10 = np.random.rand(2,8)  #taxminiy qiymatlardan iborat massiv yasaydi
arr10
arr10.shape

arr11 = np.random.randint(5, size=(2, 4))
arr11
arr11.shape

(2, 4)

In [ ]:
b = np.eye(4, dtype = float)
print("Matrix b: \n", b)
b.shape
b.size

Matrix b: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


16

In [ ]:
b.ndim

2